version: '3.2'

services:
  iris-fhir:
    build:
      context: .
    container_name: iris-fhir
    #image: store/intersystems/irishealth-community:2020.1.0.199.0
    ports:
    - "51773:51773"
    - "52773:52773"
    volumes:
    - .:/app