version: '3.7'

services:

  webinar-fhir:
    build:
      context: .
    init: true
    image: webinar-fhir
    container_name: webinar-fhir
    command: --check-caps false
    ports:
    - "51773:51773"
    - "52773:52773"
    volumes:
    - .:/app

  smartapp:
    build:
      dockerfile: Dockerfile
      context: smartapp
    container_name: smartapp
    ports:
    - "9000:9000"